# Generated by Django 4.2.13 on 2024-06-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_product_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Product',
            name='gender',
        ),
    ]
    
    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]