# Generated by Django 4.2.13 on 2024-06-05 22:20

from django.db import migrations, models


def migrate_categories(apps, schema_editor):
    Product = apps.get_model('storefront', 'Product')
    Category = apps.get_model('storefront', 'Category')
    for product in Product.objects.all():
        # Assign the first category to the new category field
        product.category = product.categories.first() if product.categories.exists() else None
        product.save()
        
        
class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_product_image_url_userprofile'),
    ]

    operations = [
         
          migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, on_delete=models.CASCADE, related_name='products', to='storefront.Category'),
        ),
         migrations.RunPython(migrate_categories),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='products', to='storefront.Category'),  # Remove default and allow NULL constraint
        ),
       
    ]

def migrate_categories(apps, schema_editor):
    Product = apps.get_model('storefront', 'Product')
    for product in Product.objects.all():
        product.category = product.categories.first()
        product.save()

 
    operations = [
      
    ]