# Generated by Django 4.2.13 on 2024-06-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_remove_product_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventory_count',
        ),
    ]
