# Generated by Django 5.0.6 on 2024-06-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_userprofile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered')], default='pending', max_length=10),
        ),
    ]
