# Generated by Django 4.2.13 on 2024-06-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0012_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
    ]
